theme: jekyll-theme-slate
show_downloads: true

github:
  zip_url: "https://github.com/GanstaKingofSA/DDLC-ModMaker/releases/download/1.2.6/DDMMaker6-1.2.6-sdk.zip",
  tar_url: "https://github.com/GanstaKingofSA/DDLC-ModMaker/releases/download/1.2.6/DDMMaker7.4-1.2.6-sdk.zip"