theme: jekyll-theme-slate
show_downloads: true

github:
  renpy6_url: "https://github.com/GanstaKingofSA/DDLC-ModMaker/releases/download/1.2.6/DDMMaker6-1.2.6-sdk.zip"
  renpy7_url: "https://github.com/GanstaKingofSA/DDLC-ModMaker/releases/download/1.2.6/DDMMaker7.4-1.2.6-sdk.zip"